Traceback (most recent call last):
  File "/home/eliott.tempez/miniconda3/envs/gbk_gff/lib/python3.12/site-packages/Bio/File.py", line 72, in as_handle
    with open(handleish, mode, **kwargs) as fp:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected str, bytes or os.PathLike object, not TextIOWrapper

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/eliott.tempez/Documents/archaea_data/convert_genbank_to_gff3.py", line 241, in <module>
    main()
  File "/home/eliott.tempez/Documents/archaea_data/convert_genbank_to_gff3.py", line 65, in main
    for gb_record in SeqIO.parse(open(args.input_file, "r"), "genbank"):
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eliott.tempez/miniconda3/envs/gbk_gff/lib/python3.12/site-packages/Bio/SeqIO/Interfaces.py", line 73, in __next__
    return next(self.records)
           ^^^^^^^^^^^^^^^^^^
  File "/home/eliott.tempez/miniconda3/envs/gbk_gff/lib/python3.12/site-packages/Bio/GenBank/Scanner.py", line 516, in parse_records
    record = self.parse(handle, do_features)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eliott.tempez/miniconda3/envs/gbk_gff/lib/python3.12/site-packages/Bio/GenBank/Scanner.py", line 499, in parse
    if self.feed(handle, consumer, do_features):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eliott.tempez/miniconda3/envs/gbk_gff/lib/python3.12/site-packages/Bio/GenBank/Scanner.py", line 470, in feed
    self._feed_feature_table(consumer, self.parse_features(skip=False))
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eliott.tempez/miniconda3/envs/gbk_gff/lib/python3.12/site-packages/Bio/GenBank/Scanner.py", line 230, in parse_features
    features.append(self.parse_feature(feature_key, feature_lines))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eliott.tempez/miniconda3/envs/gbk_gff/lib/python3.12/site-packages/Bio/GenBank/Scanner.py", line 357, in parse_feature
    assert len(qualifiers) > 0
AssertionError
